### ISSUE TITLE
set world read on saxon.jar

### ISSUE THREAD

**Issue by codefromthecrypt** [klakegg/docker-saxon#2]
right now /saxon.jar has root-only, which messes with scripts that try to set non-root user

```bash
$ docker run --rm -i -t klakegg/saxon  /bin/sh
/src # ls -al /saxon.jar 
-rw-------    1 root     root       5484426 Mar 12 18:11 /saxon.jar
```

**Comment by klakegg** [comment]
Thank you for your feedback. The `klakegg/saxon:dev` is now updated accordingly, and is bumped to Saxon 9.9.1-4. I expect to make the release in just a few days. :)
